---
- name: Host member managedby_host present
  hosts: ipaserver
  become: true

  tasks:
  - ipahost:
      ipaadmin_password: SomeADMINpassword
      name: host01.example.com
      managedby_host: server.example.com
      action: member
