---
- name: Automount map present example
  hosts: ipaserver
  become: true
  tasks:
  - name: ensure map TestMap is present
    ipaautomountmap:
      ipaadmin_password: SomeADMINpassword
      name: TestMap
      location: TestLocation
      desc: "this is a test map"

