---
- name: Servicedelegationtarget member present example
  hosts: ipaserver
  become: no

  tasks:
  - name: Ensure member test/example.com is present in servicedelegationtarget test-delegation-target
    ipaservicedelegationtarget:
     name: test-delegation-target
     principal: test/example.com
     action: member
